services:
  - type: web
    name: ai-brainstorm
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: PORT
        value: 3000
